### ISSUE TITLE
unexpected token `('

### ISSUE THREAD

**Issue by ikolsteren** [yellowspaced/tubearchivist-metadata-export#2]
Seem to be having a similar syntax issue

```
/volume1/video/get-tubearchivist-meta.py: line 1: import: command not found
/volume1/video/get-tubearchivist-meta.py: line 2: from: command not found
/volume1/video/get-tubearchivist-meta.py: line 3: import: command not found
/volume1/video/get-tubearchivist-meta.py: line 4: import: command not found
/volume1/video/get-tubearchivist-meta.py: line 5: from: command not found
/volume1/video/get-tubearchivist-meta.py: line 12: rootfile: command not found
/volume1/video/get-tubearchivist-meta.py: line 21: syntax error near unexpected token `('
/volume1/video/get-tubearchivist-meta.py: line 21: `es = Elasticsearch(['http://elastic:notmypassword@192.168.0.10:9200'])'
```
The top of my script is:
```
import os
from elasticsearch import Elasticsearch
import xml.etree.ElementTree as ET
import requests
from PIL import Image

##########################################################
### Set your file path!
### Example

rootfile = "/volume1/video/YouTube" 

es = Elasticsearch(['http://elastic:notmypassword@192.168.0.10:9200'])
```

**Comment by ikolsteren** [comment]
Might be the way I am running the common?   I tried as
`python3 get-tube archivist-meta.py`
and got
```
Traceback (most recent call last):
  File "get-tubearchivist-meta.py", line 2, in <module>
    from elasticsearch import Elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'
```

**Comment by ikolsteren** [comment]
Getting further
```
Traceback (most recent call last):
  File "/cache/get-tubearchivist-meta.py", line 28, in <module>
    for r, d, f, in os.walk(rootfile):
NameError: name 'os' is not defined. Did you mean: 'es'?
root@3c2856b547c7:/cache# 
```

**Comment by ikolsteren** [comment]
Moved to another OS and got it - :-)
